import './globals.css'
import { Inter } from 'next/font/google'
import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'
import ClientOnly from './components/ClientOnly'
import RegisterModal from './components/modals/RegisterModal'
import ToasterProvider from './providers/ToasterProvider'
import LoginModal from './components/modals/LoginModal'
import getCurrentUser from './actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })
const font = Nunito({  subsets: ['latin'] })

export const metadata = {
  title: 'Air',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // server side rendering
  const currentUser = await getCurrentUser();
  //console.log('current user:', currentUser);

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterModal />
          <LoginModal />

          {/* position fixed navgiation bar */}          
          <Navbar currentUser={currentUser} />                    
        </ClientOnly>
        {children}
        
      </body>
    </html>
  )
}
